package fr.sixczero.util;

public enum screenType {
    ADVANCEMENTS_SCREEN,
    CONNECT_SCREEN,
    DEATH_SCREEN,
    GAMEMENU_SCREEN,
    INITIALIZATION_SCREEN,
    LOADINGONLINE_SCREEN,
    LOADINGWORLD_SCREEN,
    MULTIPLAYER_SCREEN,
    OPTIONS_SCREEN,
    TITLE_SCREEN,
    UNKNOWN_SCREEN
}